<?php

/**
 * @file
 * Contains custom_drush.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_drush_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_drush module.
    case 'help.page.custom_drush':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal custom module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function custom_drush_theme() {
  return [
    'custom_drush' => [
      'template' => 'custom_drush',
      'render element' => 'children',
    ],
  ];
}
